apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: sidecar-injector-webhook-cfg
  labels:
    app: sidecar-injector
webhooks:
  - name: sidecar-injector.morven.me
    clientConfig:
      service:
        name: sidecar-injector-webhook-svc
        namespace: default
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01ETXhNVEEyTWpZeE1sb1hEVE13TURNd09UQTJNall4TWxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTkpNCjFORDUrNXBDOHRMdGJIWllra2xYbzN3NkQvNmtBMVUvUDY4MS9sMzkvK1JybnZCaU8zWThBVUhMNFBoZWdvRDMKb2lZV3NiYVE5MFNna2lLRVRFNHZqZkJMOStjTUlHRkhpY2tvb2FuQXRqNmlZazd0Rm81ZkhJNldQOW9jL2JNTAppUytHRzFDQ2tTWno1eVdhZDVPRmozL2dZRUl0WVh6bEdXUmxEVE5XZENLQmV3QzFmSzNuMU0xVlhzTkZWdUN0CktsM0xhV2FXRDNTUERnUWlvZWlaSjY3NWdKMzJJVWtiZUFHcytaYjhRSXpCZHVkbm5qdmhtOFlRak4zV1cyNHcKdnVMdnhiUEZ6bFFhWUlEb2hBQjhYMW5RZ2NyZlBwMDBhdDRRQnNZZmJ0TmNqaW9BVndyRWc4Z3MvRFFHUlhYWQpqWERscTk5bHdXRkR4dmlDcTdVQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFCSExvUW44cEE1YnlybkdlaWlKQWs1WndVbW4KbGpJSGozYUg1elJmN1VEdEVPM2dXKzJOT1NFS3lNc2VKN2M5a0ZXVFFGWjk5dTJ5Ui84MmZ4ZGRRdGNiemptcgp4RWZ2eVZLRFBWYVAwMXlVUHluTnBWcTl3ZlJBNWlyQ0pPcUo4YlJmcmd1VTRVZFNUMXE5VGNSOUltTHd1Z050Cnl6TnpGN1lwK2NhMDhxK0VJV2JjVkVnRHo1R0ZxSlpSeXVqUFlCQ0gyYnZqc2ZmUFM0enk5WVF5R0NHSFdISWIKZ3V5OExSOGFJUXJVaFM3T01kbHFBY005eDQ3MUdISU1ESENjSjJTM2hkaFZwaDBWVjZIZndMV1VFenZ1ajdBaAprbEJqT09pVkxjOWtsYmdwQ09kMWlOajRQb3UzQ09vRUw1OEI4UmthQ2NLejlxZjJtc1YxT3I2ci91QT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["shitangdama.github.io"]
        apiVersions: ["v1"]
        resources: ["debugers"]
    namespaceSelector:
      matchLabels:
        sidecar-injector: enabled