apiVersion: v1
kind: ServiceAccount
metadata:
  name: sidecar-inject-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: sidecar-inject-manager-role
rules:
  - apiGroups:
      - shitangdama.github.io
    resources:
      - debugers
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
    verbs:
      - get
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sidecar-inject-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sidecar-inject-manager-role
subjects:
  - kind: ServiceAccount
    name: sidecar-inject-manager
    namespace: default